channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.5
  - drmaa=0.7
  - snakemake-minimal=5.3.0
  - pip:
    - "git+git://github.com/lumc-pgx/locus-processing.git@master#egg=locus_processing"
    - "git+git://github.com/lumc-pgx/pipe-runner.git@master#egg=pipe_runner"
    - "git+git://github.com/lumc-pgx/pipe-helper.git@master#egg=pipe_helper"
